---
pages:
- posts/swimmers-rejoice.md
- posts/two-minutes-to-midnight.md
- posts/senate-beat.md
- posts/clothes-for-cash.md
- posts/self-service-gas.md
- posts/grammy-awards-cause-controversy.md
- posts/painting-reed.md
- posts/wordless-stories.md
- posts/state-of-disunion.md
- posts/house-advisors-fight-for-collective-bargaining-rights.md
- posts/focused-on-dissent.md
- posts/letter-from-the-hum-110-faculty.md
- posts/enough-is-enough--in-support-of-a--double-freeze--in-north-korea.md
- posts/dog-of-the-week--indie.md
- posts/courts-block-trumpian-immigration-law-again.md
- posts/students-of-color-union.md
- posts/bashful-zebrafish.md
- posts/op-ed--how-free-should-campus--free-speech--be-.md
- posts/ash-descends-over-reed-campus.md
- posts/detained-for-a-day.md
- posts/addressing-food-insecurity-at-reed.md
- posts/summer-of-trump.md
- posts/horscope.md
- posts/tree-of-the-week--the-vollum-incense-cedar.md
- posts/flu-season--a-notice-from-the-hcc.md
- posts/summary-of-judicial-board-and-title-ix-board-cases.md
- posts/a-statement-from-weapons-of-mass-distraction.md
- posts/letter-from-the-editors.md
- posts/album-review--jpegmafia-s-veteran.md
- posts/the-flu-and-you.md
- posts/summary-of-academic-misconduct-cases.md
- posts/csos-take-test-kits.md
- posts/fighting-forward.md
- posts/investment-committee-maintains-connections-to-wells-fargo.md
- posts/women-in-black.md
- posts/humanities-curriculum-crosses-the-atlantic.md
- posts/2017-09-07-students-banned-as-tensions-rise.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- type: tag_list
  name: authors
  label: Authors
  description: Authors of the article (if anonymous write "Staff")
- type: text
  name: type
  label: Type
  description: Just type "post" in here
  config:
    required: true
  default: post
- type: text
  label: URL
  name: url
  description: "/YYYY/MM/DD/Headline-goes-here/"
  config:
    required: true
- type: datetime
  name: date
  label: Date of publication
  description: Date for the articles to release
  config:
    date_format: YYYY-MM-DD
    required: true
- type: tag_list
  name: tags
  label: Tags
  description: Put article tags here
- type: tag_list
  name: categories
  label: Categories
  description: Put article categories (News, Features, Entertainment, Editorials,
    Opinion)
  default: []
- type: file
  label: Upload image
  name: image
