---
pages:
- posts/summary-of-academic-misconduct-cases.md
- posts/summary-of-judicial-board-and-title-ix-board-cases.md
- posts/csos-take-test-kits.md
- posts/fighting-forward.md
- posts/a-statement-from-weapons-of-mass-distraction.md
- posts/letter-from-the-editors.md
- posts/investment-committee-maintains-connections-to-wells-fargo.md
- posts/women-in-black.md
- posts/humanities-curriculum-crosses-the-atlantic.md
- posts/2017-09-07-students-banned-as-tensions-rise.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- type: tag_list
  name: authors
  label: Authors
  description: Authors of the article (if anonymous write "Staff")
- type: text
  name: type
  label: Type
  description: Just type "post" in here
  config:
    required: true
  default: post
- type: text
  label: URL
  name: url
  description: "/YYYY/MM/DD/Headline-goes-here/"
  config:
    required: true
- type: datetime
  name: date
  label: Date of publication
  description: Date for the articles to release
  config:
    date_format: YYYY-MM-DD
    required: true
- type: tag_list
  name: tags
  label: Tags
  description: Put article tags here
- type: tag_list
  name: categories
  label: Categories
  description: Put article categories (News, Features, Entertainment, Editorials,
    Opinion)
  default: []
- type: file
  label: Upload image
  name: image
