---
label: default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- type: tag_list
  name: authors
  label: Authors
  description: Authors of the article (if anonymous write "Staff")
- type: text
  name: type
  label: Type
  description: Just type "post" in here
  config:
    required: true
  default: post
- type: text
  label: URL
  name: url
  description: "/YYYY/MM/DD/Headline-goes-here/"
  config:
    required: true
- type: datetime
  name: date
  label: Date of publication
  description: Date for the articles to release
  config:
    date_format: YYYY-MM-DD
    required: true
- type: tag_list
  name: tags
  label: Tags
  description: Put article tags here
- type: tag_list
  name: categories
  label: Categories
  description: Put article categories (News, Features, Entertainment, Editorials,
    Opinion)
  default: []
- type: file
  label: Upload image
  name: image
pages:
- content/posts/renn-fayre-theme-sim-city--not-sin-city.md
- content/posts/tree-of-the-week--the-west-woodstock-european-beech.md
- content/posts/friday-the-thirteenth-tattoo-deals.md
- content/posts/humanities-110-enters-the-20th-century.md
- content/posts/house-advisors-fight-for-collective-bargaining-rights.md
- content/posts/focused-on-dissent.md
- content/posts/horscope.md
- content/posts/tree-of-the-week--the-vollum-incense-cedar.md
- content/posts/a-statement-from-weapons-of-mass-distraction.md
- content/posts/letter-from-the-editors.md
- content/posts/album-review--jpegmafia-s-veteran.md
- content/posts/summary-of-academic-misconduct-cases.md
- content/posts/enough-is-enough--in-support-of-a--double-freeze--in-north-korea.md
- content/posts/detained-for-a-day.md
- content/posts/dog-of-the-week--indie.md
- content/posts/grammy-awards-cause-controversy.md
- content/posts/painting-reed.md
- content/posts/summer-of-trump.md
- content/posts/senate-blurbs.md
- content/posts/behind-the-scenes-of-the-math-colloquium--math-talks--friends--and-the-poetry-of-ideas.md
- content/posts/op-ed--first-they-jail-you--then-they-kill-you--then-they-love-you.md
- content/posts/group-requirements-overturned.md
- content/posts/in-media-res.md
- content/posts/op-ed--if-senate-is-really-socialist--they-ll-abolish-themselves.md
- content/posts/new-dorm-to-be-named--the-nogdom-.md
- content/posts/gary-granger-stages-coup-d-etat--proclaims-end-of-cannabis-odor-elusion.md
- content/posts/tree-of-the-week--yuletide-camillias.md
- content/posts/senate-beat--renn-fayre-budget-heavily-cut--but-free-condoms-saved.md
- content/posts/rethinking-justice.md
- content/posts/tree-of-the-week--clbr-s-american-sycamore.md
- content/posts/two-minutes-to-midnight.md
- content/posts/self-service-gas.md
- content/posts/senate-beat.md
- content/posts/letter-from-the-hum-110-faculty.md
- content/posts/online-poll-reveals--two-students-you-actually-thought-existed.md
- content/posts/a-message-from-director-of-athletics--fitness--and-outdoor-programs-michael-lombardo.md
- content/posts/senate-beat-1.md
- content/posts/humplay-mmxviii-direktors-tell-all.md
- content/posts/clothes-for-cash.md
- content/posts/wordless-stories.md
- content/posts/state-of-disunion.md
- content/posts/summary-of-judicial-board-and-title-ix-board-cases.md
- content/posts/flu-season--a-notice-from-the-hcc.md
- content/posts/the-flu-and-you.md
- content/posts/swimmers-rejoice.md
- content/posts/csos-take-test-kits.md
- content/posts/fighting-forward.md
- content/posts/investment-committee-maintains-connections-to-wells-fargo.md
- content/posts/humanities-curriculum-crosses-the-atlantic.md
- content/posts/women-in-black.md
- content/posts/courts-block-trumpian-immigration-law-again.md
- content/posts/bashful-zebrafish.md
- content/posts/op-ed--how-free-should-campus--free-speech--be-.md
- content/posts/ash-descends-over-reed-campus.md
- content/posts/students-of-color-union.md
- content/posts/2017-09-07-students-banned-as-tensions-rise.md
- content/posts/portland-international-film-festival-brings-cinema-to-the-city.md
- content/posts/bashir-s--field-theories--receives-oregon-book-award-nomination.md
- content/posts/is-reed-s-tobacco-culture-going-up-in-smoke-.md
- content/posts/addressing-food-insecurity-at-reed.md
- content/posts/former-student-sues-reed-college--professor-over-allegations-of-discrimination-and-sexual-harassment.md
- content/authors/mariela.md
